apiVersion: v3.0.2
kind: DataContract
id: c4fb7f28-cd18-47e6-819b-2e607e558b53
version: 1.0.0
status: active
domain: inverter  
dataProduct: EnodeInverterEventBronze
tenant: Enovos
description:
  purpose: "This contract defines the data schema, service infrastructure, and service level agreements for a S3 service managing data for inverter events."
  usage: "Data available for analytics"

servers:
  - server: eventsStorage
    type: s3
    format: json
    delimiter: array
    location: s3://eno-dm-bronze-prd/enode/landing/*/*/*/inverterEvents-*.json
    description: "S3 storage service for event records"
    environment: production
  - server: eventsStorage-uat
    type: s3
    format: json
    delimiter: array
    location: s3://eno-dm-bronze-uat/enode/landing/*/*/*/inverterEvents-*.json
    description: "S3 storage service for event records"
    environment: uat

schema:  
  - name: InverterDiscoveredEvent  
    logicalType: object  
    physicalType: object  
    description: "Event emitted when a user’s inverter is discovered."  
    properties:  
      - name: createdAt  
        logicalType: date  
        description: "Timestamp when the event was created."  
        required: true  
        examples:
          - "2020-04-07T17:04:26Z"
        quality:
          - rule: timestampFormat
            type: library
            description: "Value must adhere to the ISO8601 format."
            parameters:
              expectedFormat: "YYYY-MM-DDTHH:mm:ssZ"


      - name: version  
        logicalType: string  
        physicalType: string  
        description: "Schema version of the payload."  
        required: true  
        examples:
          - "2024-10-01"
        quality:
          - rule: nonEmpty
            type: library
            description: "Version must not be empty."
            parameters:
              minLength: 1

      - name: user  
        logicalType: object  
        physicalType: object  
        description: "Reference to the user who owns the inverter."  
        required: true
        quality:
          - rule: jsonStructure
            type: library
            description: "Must be a valid JSON object containing required keys."
            parameters:
              requiredKeys: ["id"]        
        properties:  
          - name: id  
            logicalType: string  
            physicalType: string  
            description: "Unique user identifier."  
            required: true  
            examples:
              - "string"  

      - name: event  
        logicalType: string  
        physicalType: string  
        description: "Type of event."  
        required: true  
        quality:  
          - rule: validValues  
            validValues: 
                - "user:inverter:discovered"
                - "user:inverter:updated"
                - "user:inverter:deleted"
            severity: error  

      - name: inverter  
        logicalType: object  
        physicalType: object  
        description: "Details and state of the discovered inverter."  
        required: true  
        quality:
          - rule: jsonStructure
            type: library
            description: "If provided, must conform to the expected schema."
            parameters:
             requiredKeys: ["id", "userId", "vendor", "lastSeen", "isReachable", "productionState"]
        properties:  

          - name: id  
            logicalType: string  
            physicalType: uuid  
            description: "Unique inverter identifier."  
            required: true  
            examples:
              - "195d8649-ad12-4755-a9cc-44e2d40ce4d9"  

          - name: userId  
            logicalType: string  
            physicalType: uuid  
            description: "Identifier of the user to whom the inverter belongs."  
            required: true  
            examples:
              - "f9d9b134-05f3-452a-80aa-be0deb22f492"  

          - name: vendor  
            logicalType: string  
            physicalType: string  
            description: "Inverter manufacturer."  
            required: true  
            examples:
              - "ENPHASE"  

          - name: lastSeen  
            logicalType: string  
            physicalType: date-time  
            description: "Last time the inverter was seen online."  
            required: true  
            examples:
              - "2020-04-07T17:04:26Z"  

          - name: isReachable  
            logicalType: boolean  
            physicalType: boolean  
            description: "Whether the inverter is currently reachable."  
            required: true  
            examples:
              - true  

          - name: productionState  
            logicalType: object  
            physicalType: object  
            description: "Current production state of the inverter."  
            required: true  
            properties:  
              - name: productionRate  
                logicalType: number  
                physicalType: decimal  
                description: "Current production rate (W)."  
                required: true  
                examples:
                  - 0  
              - name: isProducing  
                logicalType: boolean  
                physicalType: boolean  
                description: "Whether the inverter is actively producing."  
                required: true  
                examples:
                  - true  
              - name: totalLifetimeProduction  
                logicalType: number  
                physicalType: decimal  
                description: "Cumulative lifetime energy produced (Wh)."  
                required: true  
                examples:
                  - 100152.56  
              - name: lastUpdated  
                logicalType: string  
                physicalType: date-time  
                description: "Timestamp of last production update."  
                required: true  
                examples:
                  - "2020-04-07T17:04:26Z"  

          - name: timezone  
            logicalType: string  
            physicalType: string  
            description: "Timezone of the inverter location."  
            required: true  
            examples:
              - "Europe/Oslo"  

          - name: capabilities  
            logicalType: object  
            physicalType: object  
            description: "Supported interventions by capability area."  
            required: true  
            properties:  
              - name: productionState  
                logicalType: object  
                physicalType: object  
                required: true  
                properties:  
                  - name: isCapable  
                    logicalType: boolean  
                    physicalType: boolean  
                    required: true  
                    examples:
                      - false  
                  - name: interventionIds  
                    logicalType: array  
                    physicalType: array  
                    description: "List of allowed intervention IDs."  
                    required: true  
                    items:  
                      logicalType: string  
                      physicalType: uuid  
                    examples:
                      - ["4eaeb363-296d-4ccc-a973-7805e6f400bd"]  
              - name: productionStatistics  
                logicalType: object  
                physicalType: object  
                required: true  
                properties:  
                  - name: isCapable  
                    logicalType: boolean  
                    physicalType: boolean  
                    required: true  
                    examples:
                      - false  
                  - name: interventionIds  
                    logicalType: array  
                    physicalType: array  
                    required: true  
                    items:  
                      logicalType: string  
                      physicalType: uuid  

          - name: scopes  
            logicalType: array  
            physicalType: array  
            description: "OAuth scopes granted for this inverter."  
            required: true  
            items:  
              logicalType: string  
              physicalType: string  
            examples:
              - ["inverter:read:data","inverter:read:location"]  

          - name: information  
            logicalType: object  
            physicalType: object  
            description: "Static inverter metadata."  
            required: true
            quality:
              - rule: jsonStructure
                type: library
                description: "If provided, must conform to the expected schema."
                parameters:
                 requiredKeys: ["id", "sn", "brand", "model", "siteName", "installationDate"]            
            properties:  
              - name: id  
                logicalType: string  
                physicalType: uuid  
                description: "Internal metadata identifier."  
                required: true  
                examples:
                  - "7a18eb4e-ee65-4d5b-bb7c-d8e530006b18"  
              - name: sn  
                logicalType: string  
                physicalType: string  
                description: "Serial number."  
                required: true  
                examples:
                  - "A123456789"  
              - name: brand  
                logicalType: string  
                physicalType: string  
                description: "Brand name."  
                required: true  
                examples:
                  - "Tesla"  
              - name: model  
                logicalType: string  
                physicalType: string  
                description: "Model name."  
                required: true  
                examples:
                  - "Sunny Boy"  
              - name: siteName  
                logicalType: string  
                physicalType: string  
                description: "Name of the installation site."  
                required: true  
                examples:
                  - "Sunny Plant"  
              - name: installationDate  
                logicalType: string  
                physicalType: date-time  
                description: "Date when the inverter was installed."  
                required: true  
                examples:
                  - "2020-04-07T17:04:26Z"  

          - name: location  
            logicalType: object  
            physicalType: object  
            description: "Last known GPS location of the inverter."  
            required: true  
            properties:  
              - name: id  
                logicalType: string  
                physicalType: uuid  
                description: "Location record identifier."  
                required: true  
                examples:
                  - "8d90101b-3f2f-462a-bbb4-1ed320d33bbe"  
              - name: longitude  
                logicalType: number  
                physicalType: decimal  
                description: "Longitude coordinate."  
                required: true  
                examples:
                  - 10.7197486  
              - name: latitude  
                logicalType: number  
                physicalType: decimal  
                description: "Latitude coordinate."  
                required: true  
                examples:
                  - 59.9173985  
              - name: lastUpdated  
                logicalType: string  
                physicalType: date-time  
                description: "Timestamp of last location update."  
                required: true  
                examples:
                  - "2020-04-07T17:04:26Z"  

team:
  - username: emma.korchia@enovos.eu
    role: data_steward
    dateIn: 2025-03-01
  - username: jesu.balan@enovos.eu
    role: data_reliability_engineer
    dateIn: 2025-03-01

roles:
  - role: data_owner
    access: write
    firstLevelApprovers: Reporting Manager
  - role: data_steward
    access: write
    firstLevelApprovers: Reporting Manager
  - role: data_analyst
    access: read
    firstLevelApprovers: Reporting Manager
  - role: data_scientist
    access: read
    firstLevelApprovers: Reporting Manager
  - role: data_architect
    access: read
    firstLevelApprovers: Reporting Manager
  - role: data_engineer
    access: read
    firstLevelApprovers: Reporting Manager
    secondLevelApprovers: data_engineer
  - role: data_reliability_engineer
    access: read
    firstLevelApprovers: Reporting Manager

slaProperties:  
  - property: uptime  
    value: "99,95% provided by AWS SLAs, on internal OLAs"  
  - property: maintenanceWindows  
    value: "1h30pm-2h30pm"  
  - property: responseTimes  
    value: "500ms"  
  - property: maxLoad  
    value: "200 requests in parallel"  
  - property: requestFrequency  
    value: "10 requests per second"  
  - property: supportHours  
    value: "business hours"  
  - property: responseTargets  
    value: "defined by the degree of criticality of the accident,P1 to P4"  
  - property: escalation  
    value: "first level Integration team, Secondo level Head of Service Delivery"  

customProperties:  
  - property: accessControls  
    value: "Only authorized users are allowed to view and modify data. Each access point is authenticated and audited."  
  - property: encryption  
    value: "All sensitive data transmitted to and from the servers will be encrypted using industry-standard protocols."  
  - property: compliance  
    value: "The system adheres to all applicable data protection regulations and standards."  
  - property: dataRetention  
    value: "Latest charging status, retrieved every 5 to 7 minutes and customer data retained for the entire time the customer is linked and deleted after 1 month after the link is revoked"  
  - property: changeManagementProcess  
    value: "Any updates to the database schema or modifications to the service levels must be communicated in advance to all stakeholders. Versioning and backward compatibility are maintained to ensure smooth transitions."  
  - property: acceptanceTerms  
    value: "By using the service, users agree to the terms of this data contract. Any changes to the contract will be provided with adequate notice and subject to user acceptance."  


tags:
  - Assets
  - Inverter

contractCreatedTs: "2025-03-26T14:00:00Z"
