apiVersion: v3.0.2
kind: DataContract
id: c4fb7f28-cd18-47e6-819b-2e607e568b56
version: 1.0.0
status: active
domain: inverter  
dataProduct: EnodeInverterStatisticsUpdateBronze
tenant: Enovos
description:
  purpose: "This contract defines the data schema, service infrastructure, and service level agreements for a S3 service managing data for inverter statistics update."
  usage: "Data available for analytics"

servers:
  - server: eventsStorage
    type: s3
    format: json
    delimiter: array
    location: s3://eno-dm-bronze-prd/enode/landing/*/*/*/inverterEvents-*.json
    description: "S3 storage service for event records"
    environment: production
  - server: eventsStorage-uat
    type: s3
    format: json
    delimiter: array
    location: s3://eno-dm-bronze-uat/enode/landing/*/*/*/inverterEvents-*.json
    description: "S3 storage service for event records"
    environment: uat

schema:
  - name: InverterStatisticsUpdatedEvent
    logicalType: object
    physicalType: object
    description: "Event emitted when inverter statistics are updated."
    properties:

      - name: createdAt
        logicalType: string
        physicalType: date-time
        description: "Timestamp when the event was created."
        required: true
        examples:
          - "2020-04-07T17:04:26Z"
        quality:
          - rule: timestampFormat
            type: library
            description: "Value must adhere to the ISO8601 format."
            parameters:
              expectedFormat: "YYYY-MM-DDTHH:mm:ssZ"

      - name: version
        logicalType: string
        physicalType: string
        description: "Schema version of the payload."
        required: true
        examples:
          - "2024-10-01"
        quality:
          - rule: nonEmpty
            type: library
            description: "Version must not be empty."
            parameters:
              minLength: 1

      - name: user
        logicalType: object
        physicalType: object
        description: "Reference to the user owning the inverter."
        required: true
        quality:
          - rule: jsonStructure
            type: library
            description: "Must be a valid JSON object containing required keys."
            parameters:
              requiredKeys: ["id"]  
        properties:
          - name: id
            logicalType: string
            physicalType: uuid
            description: "Unique user identifier."
            required: true
            examples:
              - "string"

      - name: event
        logicalType: string
        physicalType: string
        description: "Type of event."
        required: true
        quality:
          - rule: validValues
            validValues:
              - "user:inverter:statistics-updated"
            severity: error

      - name: statistics
        logicalType: object
        physicalType: object
        description: "Updated statistics for the inverter at various resolutions."
        required: true
        properties:

          - name: timezone
            logicalType: string
            physicalType: string
            description: "Timezone for the timestamps."
            required: false
            examples:
              - "Europe/Oslo"

          - name: resolutions
            logicalType: object
            physicalType: object
            description: "Energy statistics by resolution periods."
            required: false
            properties:

              - name: QUARTER_HOUR
                logicalType: object
                physicalType: object
                description: "Quarter-hourly energy statistics."
                required: true
                properties:
                  - name: unit
                    logicalType: string
                    physicalType: string
                    description: "Unit of measure (kWh)."
                    required: true
                    quality:
                      - rule: validValues
                        validValues: ["kWh"]
                        severity: error
                    examples:
                      - "kWh"
                  - name: data
                    logicalType: array
                    physicalType: array
                    description: "Array of timestamped values."
                    required: true
                    items:
                      logicalType: object
                      physicalType: object
                      properties:
                        - name: date
                          logicalType: string
                          physicalType: date-time
                          description: "Timestamp of the measurement."
                          required: true
                          examples:
                            - "2021-01-19T00:15:00+01:00"
                        - name: value
                          logicalType: number
                          physicalType: decimal
                          description: "Energy produced in this interval."
                          required: true
                          examples:
                            - 1.1

              - name: DAY
                logicalType: object
                physicalType: object
                description: "Daily energy statistics."
                required: true
                properties:
                  - name: unit
                    logicalType: string
                    physicalType: string
                    description: "Unit of measure (kWh)."
                    required: true
                    quality:
                      - rule: validValues
                        validValues: ["kWh"]
                        severity: error
                    examples:
                      - "kWh"
                  - name: data
                    logicalType: array
                    physicalType: array
                    description: "Array of timestamped values."
                    required: true
                    items:
                      logicalType: object
                      physicalType: object
                      properties:
                        - name: date
                          logicalType: string
                          physicalType: date-time
                          description: "Timestamp of the measurement."
                          required: true
                          examples:
                            - "2021-01-19T00:15:00+01:00"
                        - name: value
                          logicalType: number
                          physicalType: decimal
                          description: "Energy produced in this interval."
                          required: true
                          examples:
                            - 1.1

          - name: inverterId
            logicalType: string
            physicalType: uuid
            description: "Identifier of the inverter."
            required: true
            examples:
              - "string"

          - name: day
            logicalType: integer
            physicalType: integer
            description: "Day of month for the statistics."
            required: true
            examples:
              - 0

          - name: month
            logicalType: integer
            physicalType: integer
            description: "Month for the statistics."
            required: true
            examples:
              - 0

          - name: year
            logicalType: integer
            physicalType: integer
            description: "Year for the statistics."
            required: true
            examples:
              - 0

team:
  - username: emma.korchia@enovos.eu
    role: data_steward
    dateIn: 2025-03-01
  - username: jesu.balan@enovos.eu
    role: data_reliability_engineer
    dateIn: 2025-03-01

roles:
  - role: data_owner
    access: write
    firstLevelApprovers: Reporting Manager
  - role: data_steward
    access: write
    firstLevelApprovers: Reporting Manager
  - role: data_analyst
    access: read
    firstLevelApprovers: Reporting Manager
  - role: data_scientist
    access: read
    firstLevelApprovers: Reporting Manager
  - role: data_architect
    access: read
    firstLevelApprovers: Reporting Manager
  - role: data_engineer
    access: read
    firstLevelApprovers: Reporting Manager
    secondLevelApprovers: data_engineer
  - role: data_reliability_engineer
    access: read
    firstLevelApprovers: Reporting Manager

slaProperties:  
  - property: uptime  
    value: "99,95% provided by AWS SLAs, on internal OLAs"  
  - property: maintenanceWindows  
    value: "1h30pm-2h30pm"  
  - property: responseTimes  
    value: "500ms"  
  - property: maxLoad  
    value: "200 requests in parallel"  
  - property: requestFrequency  
    value: "10 requests per second"  
  - property: supportHours  
    value: "business hours"  
  - property: responseTargets  
    value: "defined by the degree of criticality of the accident,P1 to P4"  
  - property: escalation  
    value: "first level Integration team, Secondo level Head of Service Delivery"  

customProperties:  
  - property: accessControls  
    value: "Only authorized users are allowed to view and modify data. Each access point is authenticated and audited."  
  - property: encryption  
    value: "All sensitive data transmitted to and from the servers will be encrypted using industry-standard protocols."  
  - property: compliance  
    value: "The system adheres to all applicable data protection regulations and standards."  
  - property: dataRetention  
    value: "Latest charging status, retrieved every 5 to 7 minutes and customer data retained for the entire time the customer is linked and deleted after 1 month after the link is revoked"  
  - property: changeManagementProcess  
    value: "Any updates to the database schema or modifications to the service levels must be communicated in advance to all stakeholders. Versioning and backward compatibility are maintained to ensure smooth transitions."  
  - property: acceptanceTerms  
    value: "By using the service, users agree to the terms of this data contract. Any changes to the contract will be provided with adequate notice and subject to user acceptance."  


tags:
  - Assets
  - Inverter

contractCreatedTs: "2025-03-26T14:00:00Z"
