apiVersion: v3.0.2
kind: DataContract
id: c4fb7f28-cd18-47e6-819b-2e607e558b43
version: 1.0.0
status: active
domain: Data Contract for Smart charging status updated
dataProduct: EnodeSmartChargingEventBronze
tenant: Enovos
description:
  purpose: "This contract defines the data schema, service infrastructure, and service level agreements for a S3 service managing data for smart charging status updated events."
  usage: "Data available for analytics"
  
  
servers:
  - server: eventsStorage
    type: s3
    format: json
    delimiter: array
    location: s3://eno-dm-bronze-prd/enode/landing/*/*/*/vehicleEvents-*.json
    description: "S3 storage service for event records"
    environment: prod
  - server: eventsStorage-uat
    type: s3
    format: json
    delimiter: array
    location: s3://eno-dm-bronze-uat/enode/landing/*/*/*/vehicleEvents-*.json
    description: "S3 storage service for event records"
    environment: uat

schema:
  - name: SmartChargingStatusUpdatedEvent
    logicalType: object
    physicalType: object
    description: "Event emitted when a vehicle’s smart charging status is updated."
    properties:
      - name: createdAt
        logicalType: date
        description: "Timestamp when the event was created."
        required: true
        examples:
          - "2020-04-07T17:04:26Z"
        quality:
          - rule: timestampFormat
            type: library
            description: "Value must adhere to the ISO8601 format."
            parameters:
              expectedFormat: "YYYY-MM-DDTHH:mm:ssZ"

      - name: version
        businessName: "Event Version"
        logicalType: string
        physicalType: string
        description: "Version of the event schema."
        required: true
        examples:
          - "2024-10-01"
        quality:
          - rule: nonEmpty
            type: library
            description: "Version must not be empty."
            parameters:
              minLength: 1

      - name: user
        logicalType: object
        physicalType: object
        description: "Reference to the user who owns the vehicle."
        required: true
        properties:
          - name: id
            logicalType: string
            physicalType: uuid
            description: "Unique user identifier."
            required: true
            examples:
              - "string"
        quality:
          - rule: jsonStructure
            type: library
            description: "Must be a valid JSON object containing required keys."
            parameters:
              requiredKeys: ["id"]
  
      - name: event
        logicalType: string
        physicalType: string
        description: "Type of event."
        required: true
        quality:
          - rule: validValues
            validValues:
              - "user:vehicle:smart-charging-status-updated"
            severity: error

      - name: smartChargingStatus
        logicalType: object
        physicalType: object
        description: "Details of the updated smart charging status."
        required: true
        quality:
          - rule: jsonStructure
            type: library
            description: "If provided, must conform to the expected vehicle schema."
            parameters:
              requiredKeys: ["updatedAt", "vehicleId", "userId", "vendor", "state", "stateChangedAt", "consideration"]
        properties:
          - name: updatedAt
            logicalType: string
            physicalType: date-time
            description: "Timestamp when the smart charging status was updated."
            required: true
            examples:
              - "2020-04-07T17:04:26Z"

          - name: vehicleId
            logicalType: string
            physicalType: uuid
            description: "Identifier of the vehicle."
            required: true
            examples:
              - "4b5ada14-ea87-4ca1-aab9-3c979c34cf4a"

          - name: userId
            logicalType: string
            physicalType: uuid
            description: "Identifier of the user for the vehicle."
            required: true
            examples:
              - "3b568b76-e30a-426e-aacd-609db4d7be81"

          - name: vendor
            logicalType: string
            physicalType: string
            description: "Vehicle vendor."
            required: true
            examples:
              - "string"

          - name: state
            logicalType: string
            physicalType: string
            description: "Current smart charging state."
            required: true
            examples:
              - "PLAN:EXECUTING:STARTING"

          - name: stateChangedAt
            logicalType: string
            physicalType: date-time
            description: "Timestamp when the state last changed."
            required: true
            examples:
              - "2020-04-07T17:04:26Z"

          - name: consideration
            logicalType: object
            physicalType: object
            description: "Contextual flags considered in the smart charging decision."
            required: true
            properties:
              - name: isPluggedIn
                logicalType: boolean
                physicalType: boolean
                description: "Whether vehicle is plugged in."
                required: true
                examples:
                  - true
              - name: isCharging
                logicalType: boolean
                physicalType: boolean
                description: "Whether vehicle is charging."
                required: true
                examples:
                  - true
              - name: atChargingLocation
                logicalType: boolean
                physicalType: boolean
                description: "Whether vehicle is at a charging location."
                required: true
                examples:
                  - true
              - name: hasTimeEstimate
                logicalType: boolean
                physicalType: boolean
                description: "Whether a finish-time estimate is available."
                required: true
                examples:
                  - true

          - name: plan
            logicalType: object
            physicalType: object
            description: "Details of the smart charging plan."
            required: true
            properties:
              - name: id
                logicalType: string
                physicalType: uuid
                description: "Identifier of the charging plan."
                required: true
                examples:
                  - "53559d39-019a-443b-a2a7-a2ca29f54d4b"
              - name: vehicleId
                logicalType: string
                physicalType: uuid
                description: "Vehicle identifier associated with the plan."
                required: true
              - name: userId
                logicalType: string
                physicalType: uuid
                description: "User identifier associated with the plan."
                required: true
              - name: locationId
                logicalType: string
                physicalType: uuid
                description: "Charging location identifier."
                required: true
              - name: vendor
                logicalType: string
                physicalType: string
                description: "Vendor handling the plan."
                required: true
              - name: currency
                logicalType: string
                physicalType: string
                description: "Currency of cost values (ISO 4217)."
                required: true
                examples:
                  - "USD"
              - name: nonSmartCost
                logicalType: number
                physicalType: decimal
                description: "Cost without smart charging (e.g., USD)."
                required: true
                examples:
                  - 17.2
              - name: smartCost
                logicalType: number
                physicalType: decimal
                description: "Cost with smart charging."
                required: true
                examples:
                  - 12.8
              - name: startAt
                logicalType: string
                physicalType: date-time
                description: "Planned start timestamp."
                required: true
              - name: stopAt
                logicalType: string
                physicalType: date-time
                description: "Planned stop timestamp."
                required: true
              - name: estimatedFinishAt
                logicalType: string
                physicalType: date-time
                description: "Estimated finish timestamp."
                required: true
              - name: startConfirmedAt
                logicalType: string
                physicalType: date-time
                description: "Timestamp when start was confirmed."
                required: true
              - name: stopConfirmedAt
                logicalType: string
                physicalType: date-time
                description: "Timestamp when stop was confirmed."
                required: true
              - name: endedAt
                logicalType: string
                physicalType: date-time
                description: "Timestamp when plan ended."
                required: true
              - name: finalState
                logicalType: string
                physicalType: string
                description: "Final state of the plan."
                required: true
                examples:
                  - "PLAN:ENDED:FINISHED"
              - name: failureCondition
                logicalType: string
                physicalType: string
                description: "Condition causing plan failure, if any."
                required: true
                examples:
                  - "CHARGE_INTERRUPTED"

          - name: smartOverride
            logicalType: object
            physicalType: object
            description: "User-initiated override of smart charging."
            required: true
            properties:
              - name: createdAt
                logicalType: string
                physicalType: date-time
                description: "Timestamp when override was created."
                required: true
                examples:
                  - "2020-04-07T17:04:26Z"
              - name: endedAt
                logicalType: string
                physicalType: date-time
                description: "Timestamp when override ended."
                required: true
                examples:
                  - "2020-04-07T17:04:26Z"
              - name: targetType
                logicalType: string
                physicalType: string
                description: "Type of override target (e.g., vehicle)."
                required: true
                examples:
                  - "vehicle"
              - name: targetId
                logicalType: string
                physicalType: uuid
                description: "Identifier of the override target."
                required: true
              - name: vendorActionId
                logicalType: string
                physicalType: uuid
                description: "Vendor-provided action identifier."
                required: true

      - name: updatedFields
        logicalType: array
        physicalType: array
        description: "List of fields updated in this event."
        required: true
        items:
          logicalType: string
          physicalType: string
        examples:
          - ["state","plan","smartOverride"]

team:
  - username: emma.korchia@enovos.eu
    role: data_steward
    dateIn: 2025-03-01
  - username: jesu.balan@enovos.eu
    role: data_reliability_engineer
    dateIn: 2025-03-01

roles:
  - role: data_owner
    access: write
    firstLevelApprovers: Reporting Manager
  - role: data_steward
    access: write
    firstLevelApprovers: Reporting Manager
  - role: data_analyst
    access: read
    firstLevelApprovers: Reporting Manager
  - role: data_scientist
    access: read
    firstLevelApprovers: Reporting Manager
  - role: data_architect
    access: read
    firstLevelApprovers: Reporting Manager
  - role: data_engineer
    access: read
    firstLevelApprovers: Reporting Manager
    secondLevelApprovers: data_engineer
  - role: data_reliability_engineer
    access: read
    firstLevelApprovers: Reporting Manager

slaProperties:  
  - property: uptime  
    value: "99,95% provided by AWS SLAs, on internal OLAs"  
  - property: maintenanceWindows  
    value: "1h30pm-2h30pm"  
  - property: responseTimes  
    value: "500ms"  
  - property: maxLoad  
    value: "200 requests in parallel"  
  - property: requestFrequency  
    value: "10 requests per second"  
  - property: supportHours  
    value: "business hours"  
  - property: responseTargets  
    value: "defined by the degree of criticality of the accident,P1 to P4"  
  - property: escalation  
    value: "first level Integration team, Secondo level Head of Service Delivery"  

customProperties:  
  - property: accessControls  
    value: "Only authorized users are allowed to view and modify data. Each access point is authenticated and audited."  
  - property: encryption  
    value: "All sensitive data transmitted to and from the servers will be encrypted using industry-standard protocols."  
  - property: compliance  
    value: "The system adheres to all applicable data protection regulations and standards."  
  - property: dataRetention  
    value: "Latest charging status, retrieved every 5 to 7 minutes and customer data retained for the entire time the customer is linked and deleted after 1 month after the link is revoked"  
  - property: changeManagementProcess  
    value: "Any updates to the database schema or modifications to the service levels must be communicated in advance to all stakeholders. Versioning and backward compatibility are maintained to ensure smooth transitions."  
  - property: acceptanceTerms  
    value: "By using the service, users agree to the terms of this data contract. Any changes to the contract will be provided with adequate notice and subject to user acceptance."  


tags:
  - Assets
  - Vehicle

contractCreatedTs: "2025-03-26T14:00:00Z"